version: '3.8'

services:
  backend:
    container_name: boss_monster_backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    networks:
      - my_network

  frontend:
    container_name: boss_monster_frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    environment:
      REACT_APP_BACKEND_URL: https://boss-monster-backend.adrwal.pl
    ports:
      - "3006:3006"
    depends_on:
      - backend
    networks:
      - my_network

networks:
  my_network:
    driver: bridge
