version: '3.8'

services:
  backend:
    container_name: boss_monster_backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    # env_file:
    #   - .env.db
    ports:
      - "3001:3001"
    # volumes:
    #   - ./data:/var/lib/postgresql/data
    networks:
      - my_network

  frontend:
    container_name: boss_monster_frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    # env_file:
    #   - .env.files-server
    ports:
      - "3006:3006"
    depends_on:
      - backend
    networks:
      - my_network

networks:
  my_network:
    driver: bridge
